#include <SFML/Graphics.hpp>
using namespace sf;

const int H = 192; //60
const int W = 25; // 20

String TileMap[H] = {
// финальная картинка
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
// 3 лвл
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",

"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",

"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",

"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",

"X                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
// 2 ЛВЛ
"Z                  C    C",
"C         C        C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C             CCCCCC    C",
"C                 CC    C",
"C                  C    C",
"C                  C    C",
"C        CC        C    C",
"C    C    C        C    C",

"L                  C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"C    C             C    C",
"C                  C    C",
"C                  C    C",
"CC   C             C    C",
"CC                 C    C",
"C           C      C    C",
"C                  C    C",
"C                  C    C",

"K                  C    C",
"C                 CC    C",
"C                  C    C",
"CCCCCC             C    C",
"CCCCCC             C    C",
"CCCCCC    CCCCCC   C    C",
"CCCCCC    CCCCCC   C    C",
"C                  C    C",
"C                  C    C",
"CCCCCC    CCC      C    C",
"CCCCCC     CC      C    C",
"CCCC               C    C",

"JCC                C    C",
"CC                CC    C",
"C                 CC    C",
"C                  C    C",
"C          CC      C    C",
"C           C      C    C",
"C                  C    C",
"C                  C    C",
"C    C             C    C",
"C    CCC           C    C",
"C                  C    C",
"C                  C    C",

"H                  C    C",
"C        CC        C    C",
"C        CC        C    C",
"C                  C    C",
"CCCC            CCCC    C",
"CC                CC    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"CC  CC  CC  CC  CCCC    C",
"CC  CC  CC  CC  CCCC    C",
"CC  CC  CC  CC  CCCC    C",
// 1 ЛВЛ
"G                  C    C",
"C                  C    C",
"C     C            C    C",
"C    C             C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"CC                 C    C",
"CC   C             C    C",
"CC   C             C    C",
"C                  C    C",
"C        CC        C    C",

"F                  C    C",
"C                  C    C",
"C           C      C    C",
"C           CC     C    C",
"C            C     C    C",
"C            C     C    C",
"C                  C    C",
"C                  C    C",
"C       C    C   C C    C",
"C                  C    C",
"C                  C    C",
"CC                 C    C",

"D                  C    C",
"C                  C    C",
"C                  C    C",
"C        CCC       C    C",
"C                  C    C",
"C                  C    C",
"C       CCC  CC    C    C",
"C                  C    C",
"C                  C    C",
"CCC                C    C",
"CC                 C    C",
"C                  C    C",

"S                  C    C",
"C       CC         C    C",
"C                  C    C",
"C                  C    C",
"C                  C    C",
"CCC                C    C",
"CCC   C            C    C",
"CCC   C      C     C    C",
"C                CCC    C",
"C                  C    C",
"C            CC    C    C",
"C                  C    C",

"A                  C    C",
"C       CCC        C    C",
"C       CCC        C    C",
"C                  C    C",
"C                  C    C",
"C             RCCCCC    C",
"CCCCC        RRC        C",
"CCCCC        OC         C",
"CCCCC        C          C",
"CCCCC        C          C",
"CCCCC        C          C",
"CCCCCCCCCCCCCCCCCCCCCCCCC",
};
